/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import bitcamp.myapp.menu.MainMenu;
import bitcamp.util.Prompt;

public class App {
  /*public String getGreeting() {
  return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }*/


  public static void main(String[] args) {
    MainMenu.execute();
    Prompt.close();
  }
}