/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import bitcamp.menu.MenuGroup;
import bitcamp.menu.MenuItem;
import bitcamp.myapp.handler.assignment.AssignmentRepository;
import bitcamp.myapp.handler.assignment.AssignmentAddHandler;
import bitcamp.myapp.handler.assignment.AssignmentViewHandler;
import bitcamp.myapp.handler.assignment.AssignmentModifyHandler;
import bitcamp.myapp.handler.assignment.AssignmentDeleteHandler;
import bitcamp.myapp.handler.assignment.AssignmentListHandler;

import bitcamp.util.Prompt;

public class App {
  /*public String getGreeting() {
  return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }*/


  public static void main(String[] args) throws Exception {
    Prompt prompt = new Prompt(System.in);

    AssignmentRepository assignmentRepository = new AssignmentRepository();

    MenuGroup mainMenu = new MenuGroup("메인");

    MenuGroup assignmentMenu = new MenuGroup("과제");
    assignmentMenu.add(new MenuItem("등록", new AssignmentAddHandler(assignmentRepository, prompt)));
    assignmentMenu.add(new MenuItem("조회", new AssignmentViewHandler(assignmentRepository, prompt)));
    assignmentMenu.add(new MenuItem("수정", new AssignmentModifyHandler(assignmentRepository, prompt)));
    assignmentMenu.add(new MenuItem("삭제", new AssignmentDeleteHandler(assignmentRepository, prompt)));
    assignmentMenu.add(new MenuItem("목록", new AssignmentListHandler(assignmentRepository, prompt)));
    mainMenu.add(assignmentMenu);
    prompt.close();
  }
}